// vocab.js — shared Korean→English vocabulary for Hangul Type practice + battle.
// Loaded synchronously before each page's main inline script. Edit freely.
window.BATTLE_VOCAB = [

  // ── People & Relationships ──────────────────────────────────────────
  { ko: '나', en: 'I / me', topikLevel: 1 },
  { ko: '우리', en: 'we / our', topikLevel: 1 },
  { ko: '너', en: 'you', topikLevel: 1 },
  { ko: '저', en: 'I (formal)', topikLevel: 1 },
  { ko: '남자', en: 'man / male', topikLevel: 1 },
  { ko: '여자', en: 'woman / female', topikLevel: 1 },
  { ko: '아이', en: 'child', topikLevel: 1 },
  { ko: '어른', en: 'adult', topikLevel: 1 },
  { ko: '부모', en: 'parents', topikLevel: 1 },
  { ko: '형', en: 'older brother (male)', topikLevel: 1 },
  { ko: '오빠', en: 'older brother (female)', topikLevel: 1 },
  { ko: '누나', en: 'older sister (male)', topikLevel: 1 },
  { ko: '남편', en: 'husband', topikLevel: 1 },
  { ko: '아내', en: 'wife', topikLevel: 1 },
  { ko: '아들', en: 'son', topikLevel: 1 },
  { ko: '딸', en: 'daughter', topikLevel: 1 },
  { ko: '남동생', en: 'younger brother', topikLevel: 1 },
  { ko: '여동생', en: 'younger sister', topikLevel: 1 },
  { ko: '삼촌', en: 'uncle', topikLevel: 1 },
  { ko: '이모', en: 'aunt (maternal)', topikLevel: 1 },
  { ko: '고모', en: 'aunt (paternal)', topikLevel: 1 },
  { ko: '사촌', en: 'cousin', topikLevel: 2 },
  { ko: '조카', en: 'nephew / niece', topikLevel: 2 },
  { ko: '이웃', en: 'neighbor', topikLevel: 1 },
  { ko: '선생님', en: 'teacher', topikLevel: 1 },
  { ko: '학생', en: 'student', topikLevel: 1 },
  { ko: '선배', en: 'senior', topikLevel: 2 },
  { ko: '후배', en: 'junior', topikLevel: 2 },
  { ko: '남녀', en: 'men and women', topikLevel: 2 },
  { ko: '외국인', en: 'foreigner', topikLevel: 1 },

  // ── Body ────────────────────────────────────────────────────────────
  { ko: '머리', en: 'head / hair', topikLevel: 1 },
  { ko: '얼굴', en: 'face', topikLevel: 1 },
  { ko: '코', en: 'nose', topikLevel: 1 },
  { ko: '목', en: 'neck / throat', topikLevel: 1 },
  { ko: '어깨', en: 'shoulder', topikLevel: 1 },
  { ko: '팔', en: 'arm', topikLevel: 1 },
  { ko: '다리', en: 'leg', topikLevel: 1 },
  { ko: '배', en: 'stomach / belly', topikLevel: 1 },
  { ko: '등', en: 'back', topikLevel: 1 },
  { ko: '가슴', en: 'chest', topikLevel: 1 },
  { ko: '뼈', en: 'bone', topikLevel: 2 },
  { ko: '피부', en: 'skin', topikLevel: 2 },
  { ko: '이', en: 'tooth / teeth', topikLevel: 1 },
  { ko: '혀', en: 'tongue', topikLevel: 2 },
  { ko: '손가락', en: 'finger', topikLevel: 1 },
  { ko: '발가락', en: 'toe', topikLevel: 1 },
  { ko: '무릎', en: 'knee', topikLevel: 2 },
  { ko: '허리', en: 'waist / lower back', topikLevel: 1 },

  // ── Daily Life ──────────────────────────────────────────────────────
  { ko: '하루', en: 'one day / a day', topikLevel: 1 },
  { ko: '생활', en: 'daily life', topikLevel: 1 },
  { ko: '주소', en: 'address', topikLevel: 1 },
  { ko: '전화', en: 'phone call', topikLevel: 1 },
  { ko: '전화번호', en: 'phone number', topikLevel: 1 },
  { ko: '일상', en: 'everyday life', topikLevel: 2 },
  { ko: '습관', en: 'habit', topikLevel: 2 },
  { ko: '준비', en: 'preparation', topikLevel: 1 },
  { ko: '청소', en: 'cleaning', topikLevel: 1 },
  { ko: '빨래', en: 'laundry', topikLevel: 1 },
  { ko: '요리', en: 'cooking', topikLevel: 1 },
  { ko: '설거지', en: 'washing dishes', topikLevel: 1 },
  { ko: '낮잠', en: 'nap', topikLevel: 2 },
  { ko: '산책', en: 'walk / stroll', topikLevel: 1 },
  { ko: '샤워', en: 'shower', topikLevel: 1 },
  { ko: '목욕', en: 'bath', topikLevel: 1 },
  { ko: '잠', en: 'sleep', topikLevel: 1 },
  { ko: '꿈', en: 'dream', topikLevel: 1 },
  { ko: '열쇠', en: 'key', topikLevel: 1 },
  { ko: '지갑', en: 'wallet', topikLevel: 1 },
  { ko: '가방', en: 'bag', topikLevel: 1 },
  { ko: '우산', en: 'umbrella', topikLevel: 1 },
  { ko: '거울', en: 'mirror', topikLevel: 1 },
  { ko: '시계', en: 'clock / watch', topikLevel: 1 },
  { ko: '안경', en: 'glasses', topikLevel: 1 },

  // ── Food & Drink ────────────────────────────────────────────────────
  { ko: '국', en: 'soup', topikLevel: 1 },
  { ko: '찌개', en: 'stew', topikLevel: 1 },
  { ko: '반찬', en: 'side dish', topikLevel: 1 },
  { ko: '고추', en: 'chili pepper', topikLevel: 1 },
  { ko: '마늘', en: 'garlic', topikLevel: 1 },
  { ko: '양파', en: 'onion', topikLevel: 1 },
  { ko: '감자', en: 'potato', topikLevel: 1 },
  { ko: '당근', en: 'carrot', topikLevel: 1 },
  { ko: '배추', en: 'napa cabbage', topikLevel: 1 },
  { ko: '계란', en: 'egg', topikLevel: 1 },
  { ko: '닭고기', en: 'chicken (meat)', topikLevel: 1 },
  { ko: '돼지고기', en: 'pork', topikLevel: 1 },
  { ko: '소고기', en: 'beef', topikLevel: 1 },
  { ko: '생선', en: 'fish', topikLevel: 1 },
  { ko: '바나나', en: 'banana', topikLevel: 1 },
  { ko: '딸기', en: 'strawberry', topikLevel: 1 },
  { ko: '포도', en: 'grape', topikLevel: 1 },
  { ko: '오렌지', en: 'orange', topikLevel: 1 },
  { ko: '수박', en: 'watermelon', topikLevel: 1 },
  { ko: '귤', en: 'tangerine', topikLevel: 1 },
  { ko: '복숭아', en: 'peach', topikLevel: 1 },
  { ko: '소금', en: 'salt', topikLevel: 1 },
  { ko: '설탕', en: 'sugar', topikLevel: 1 },
  { ko: '간장', en: 'soy sauce', topikLevel: 1 },
  { ko: '기름', en: 'oil', topikLevel: 1 },
  { ko: '밀가루', en: 'flour', topikLevel: 1 },
  { ko: '쌀', en: 'rice (uncooked)', topikLevel: 1 },
  { ko: '면', en: 'noodle', topikLevel: 1 },
  { ko: '떡', en: 'rice cake', topikLevel: 1 },
  { ko: '과자', en: 'snack / cookie', topikLevel: 1 },
  { ko: '케이크', en: 'cake', topikLevel: 1 },
  { ko: '아이스크림', en: 'ice cream', topikLevel: 1 },
  { ko: '초콜릿', en: 'chocolate', topikLevel: 1 },
  { ko: '주스', en: 'juice', topikLevel: 1 },
  { ko: '맥주', en: 'beer', topikLevel: 1 },
  { ko: '소주', en: 'soju', topikLevel: 1 },
  { ko: '녹차', en: 'green tea', topikLevel: 1 },
  { ko: '홍차', en: 'black tea', topikLevel: 1 },
  { ko: '음료', en: 'beverage', topikLevel: 1 },
  { ko: '냉면', en: 'cold noodles', topikLevel: 1 },
  { ko: '비빔밥', en: 'bibimbap', topikLevel: 1 },
  { ko: '삼겹살', en: 'pork belly', topikLevel: 1 },
  { ko: '치킨', en: 'fried chicken', topikLevel: 1 },
  { ko: '피자', en: 'pizza', topikLevel: 1 },
  { ko: '햄버거', en: 'hamburger', topikLevel: 1 },
  { ko: '맛', en: 'taste / flavor', topikLevel: 1 },

  // ── Time & Date ─────────────────────────────────────────────────────
  { ko: '월요일', en: 'Monday', topikLevel: 1 },
  { ko: '화요일', en: 'Tuesday', topikLevel: 1 },
  { ko: '수요일', en: 'Wednesday', topikLevel: 1 },
  { ko: '년', en: 'year', topikLevel: 1 },
  { ko: '월', en: 'month', topikLevel: 1 },
  { ko: '날', en: 'day', topikLevel: 1 },
  { ko: '주', en: 'week', topikLevel: 1 },
  { ko: '초', en: 'second', topikLevel: 1 },
  { ko: '아까', en: 'a moment ago', topikLevel: 1 },
  { ko: '나중', en: 'later', topikLevel: 1 },
  { ko: '먼저', en: 'first / before', topikLevel: 1 },
  { ko: '항상', en: 'always', topikLevel: 1 },
  { ko: '보통', en: 'usually', topikLevel: 1 },
  { ko: '자주', en: 'often', topikLevel: 1 },
  { ko: '가끔', en: 'sometimes', topikLevel: 1 },
  { ko: '거의', en: 'almost / hardly', topikLevel: 1 },
  { ko: '이미', en: 'already', topikLevel: 1 },
  { ko: '아직', en: 'yet / still', topikLevel: 1 },
  { ko: '드디어', en: 'finally', topikLevel: 2 },
  { ko: '갑자기', en: 'suddenly', topikLevel: 2 },
  { ko: '오래', en: 'for a long time', topikLevel: 1 },
  { ko: '잠깐', en: 'for a moment', topikLevel: 1 },
  { ko: '올해', en: 'this year', topikLevel: 1 },
  { ko: '내년', en: 'next year', topikLevel: 1 },
  { ko: '작년', en: 'last year', topikLevel: 1 },
  { ko: '이번', en: 'this time / this', topikLevel: 1 },
  { ko: '다음', en: 'next', topikLevel: 1 },
  { ko: '지난', en: 'last / past', topikLevel: 1 },
  { ko: '낮', en: 'daytime / noon', topikLevel: 1 },
  { ko: '밤', en: 'night', topikLevel: 1 },
  { ko: '새벽', en: 'dawn / early morning', topikLevel: 1 },
  { ko: '오전', en: 'morning / AM', topikLevel: 1 },
  { ko: '오후', en: 'afternoon / PM', topikLevel: 1 },

  // ── Weather & Nature ────────────────────────────────────────────────
  { ko: '날씨', en: 'weather', topikLevel: 1 },
  { ko: '햇빛', en: 'sunlight', topikLevel: 1 },
  { ko: '구름', en: 'cloud', topikLevel: 1 },
  { ko: '바람', en: 'wind', topikLevel: 1 },
  { ko: '눈보라', en: 'blizzard', topikLevel: 2 },
  { ko: '안개', en: 'fog', topikLevel: 1 },
  { ko: '번개', en: 'lightning', topikLevel: 1 },
  { ko: '천둥', en: 'thunder', topikLevel: 1 },
  { ko: '태풍', en: 'typhoon', topikLevel: 1 },
  { ko: '홍수', en: 'flood', topikLevel: 2 },
  { ko: '가뭄', en: 'drought', topikLevel: 2 },
  { ko: '봄', en: 'spring', topikLevel: 1 },
  { ko: '여름', en: 'summer', topikLevel: 1 },
  { ko: '가을', en: 'autumn / fall', topikLevel: 1 },
  { ko: '겨울', en: 'winter', topikLevel: 1 },
  { ko: '기온', en: 'temperature', topikLevel: 1 },
  { ko: '강', en: 'river', topikLevel: 1 },
  { ko: '바다', en: 'sea / ocean', topikLevel: 1 },
  { ko: '호수', en: 'lake', topikLevel: 1 },
  { ko: '땅', en: 'ground / land', topikLevel: 1 },
  { ko: '돌', en: 'stone / rock', topikLevel: 1 },
  { ko: '풀', en: 'grass', topikLevel: 1 },
  { ko: '숲', en: 'forest', topikLevel: 1 },
  { ko: '들', en: 'field / plain', topikLevel: 1 },
  { ko: '하늘색', en: 'sky blue', topikLevel: 1 },
  { ko: '달', en: 'moon', topikLevel: 1 },
  { ko: '별', en: 'star', topikLevel: 1 },
  { ko: '해', en: 'sun', topikLevel: 1 },
  { ko: '공기', en: 'air', topikLevel: 1 },
  { ko: '나뭇잎', en: 'leaf', topikLevel: 1 },

  // ── Places ──────────────────────────────────────────────────────────
  { ko: '나라', en: 'country', topikLevel: 1 },
  { ko: '도시', en: 'city', topikLevel: 1 },
  { ko: '마을', en: 'village / town', topikLevel: 1 },
  { ko: '서울', en: 'Seoul', topikLevel: 1 },
  { ko: '부산', en: 'Busan', topikLevel: 1 },
  { ko: '거리', en: 'street / distance', topikLevel: 1 },
  { ko: '광장', en: 'plaza / square', topikLevel: 2 },
  { ko: '식당', en: 'restaurant', topikLevel: 1 },
  { ko: '카페', en: 'cafe', topikLevel: 1 },
  { ko: '편의점', en: 'convenience store', topikLevel: 1 },
  { ko: '백화점', en: 'department store', topikLevel: 1 },
  { ko: '마트', en: 'mart / supermarket', topikLevel: 1 },
  { ko: '약국', en: 'pharmacy', topikLevel: 1 },
  { ko: '경찰서', en: 'police station', topikLevel: 1 },
  { ko: '우체국', en: 'post office', topikLevel: 1 },
  { ko: '호텔', en: 'hotel', topikLevel: 1 },
  { ko: '공원', en: 'park', topikLevel: 1 },
  { ko: '극장', en: 'theater', topikLevel: 1 },
  { ko: '미술관', en: 'art museum', topikLevel: 2 },
  { ko: '박물관', en: 'museum', topikLevel: 1 },
  { ko: '수영장', en: 'swimming pool', topikLevel: 1 },
  { ko: '운동장', en: 'sports field', topikLevel: 1 },
  { ko: '교실', en: 'classroom', topikLevel: 1 },
  { ko: '사무실', en: 'office', topikLevel: 1 },
  { ko: '주차장', en: 'parking lot', topikLevel: 1 },
  { ko: '지하', en: 'underground', topikLevel: 1 },
  { ko: '계단', en: 'stairs', topikLevel: 1 },
  { ko: '엘리베이터', en: 'elevator', topikLevel: 1 },
  { ko: '입구', en: 'entrance', topikLevel: 1 },
  { ko: '출구', en: 'exit', topikLevel: 1 },

  // ── Transportation ──────────────────────────────────────────────────
  { ko: '기차', en: 'train', topikLevel: 1 },
  { ko: '비행기', en: 'airplane', topikLevel: 1 },
  { ko: '자동차', en: 'car / automobile', topikLevel: 1 },
  { ko: '자전거', en: 'bicycle', topikLevel: 1 },
  { ko: '오토바이', en: 'motorcycle', topikLevel: 1 },
  { ko: '역', en: 'station', topikLevel: 1 },
  { ko: '정류장', en: 'bus stop', topikLevel: 1 },
  { ko: '신호등', en: 'traffic light', topikLevel: 1 },
  { ko: '교통', en: 'traffic / transport', topikLevel: 1 },
  { ko: '좌석', en: 'seat', topikLevel: 1 },
  { ko: '짐', en: 'luggage / load', topikLevel: 1 },
  { ko: '표', en: 'ticket', topikLevel: 1 },
  { ko: '항공권', en: 'airline ticket', topikLevel: 2 },
  { ko: '여권', en: 'passport', topikLevel: 1 },

  // ── Shopping & Money ────────────────────────────────────────────────
  { ko: '가격', en: 'price', topikLevel: 1 },
  { ko: '돈', en: 'money', topikLevel: 1 },
  { ko: '원', en: 'Korean won', topikLevel: 1 },
  { ko: '계산', en: 'calculation / bill', topikLevel: 1 },
  { ko: '할인', en: 'discount', topikLevel: 1 },
  { ko: '영수증', en: 'receipt', topikLevel: 1 },
  { ko: '카드', en: 'card', topikLevel: 1 },
  { ko: '현금', en: 'cash', topikLevel: 1 },
  { ko: '쇼핑', en: 'shopping', topikLevel: 1 },
  { ko: '물건', en: 'item / thing', topikLevel: 1 },
  { ko: '선물', en: 'gift', topikLevel: 1 },
  { ko: '포장', en: 'packaging / wrapping', topikLevel: 2 },
  { ko: '교환', en: 'exchange', topikLevel: 2 },
  { ko: '환불', en: 'refund', topikLevel: 2 },
  { ko: '세일', en: 'sale', topikLevel: 1 },
  { ko: '브랜드', en: 'brand', topikLevel: 2 },
  { ko: '사이즈', en: 'size', topikLevel: 1 },

  // ── School ──────────────────────────────────────────────────────────
  { ko: '공부', en: 'study', topikLevel: 1 },
  { ko: '수업', en: 'class / lesson', topikLevel: 1 },
  { ko: '시험', en: 'exam / test', topikLevel: 1 },
  { ko: '숙제', en: 'homework', topikLevel: 1 },
  { ko: '교과서', en: 'textbook', topikLevel: 1 },
  { ko: '공책', en: 'notebook', topikLevel: 1 },
  { ko: '연필', en: 'pencil', topikLevel: 1 },
  { ko: '볼펜', en: 'ballpoint pen', topikLevel: 1 },
  { ko: '지우개', en: 'eraser', topikLevel: 1 },
  { ko: '칠판', en: 'blackboard', topikLevel: 1 },
  { ko: '성적', en: 'grade / score', topikLevel: 1 },
  { ko: '졸업', en: 'graduation', topikLevel: 1 },
  { ko: '입학', en: 'school admission', topikLevel: 2 },
  { ko: '대학교', en: 'university', topikLevel: 1 },
  { ko: '중학교', en: 'middle school', topikLevel: 1 },
  { ko: '고등학교', en: 'high school', topikLevel: 1 },
  { ko: '초등학교', en: 'elementary school', topikLevel: 1 },
  { ko: '방학', en: 'school break', topikLevel: 1 },
  { ko: '도서관', en: 'library', topikLevel: 1 },
  { ko: '동아리', en: 'club / circle', topikLevel: 2 },
  { ko: '과목', en: 'subject', topikLevel: 2 },
  { ko: '수학', en: 'math', topikLevel: 1 },
  { ko: '과학', en: 'science', topikLevel: 1 },
  { ko: '역사', en: 'history', topikLevel: 1 },
  { ko: '음악', en: 'music', topikLevel: 1 },
  { ko: '미술', en: 'art', topikLevel: 1 },
  { ko: '체육', en: 'physical education', topikLevel: 1 },
  { ko: '국어', en: 'Korean language', topikLevel: 1 },

  // ── Work & Jobs ─────────────────────────────────────────────────────
  { ko: '직업', en: 'job / occupation', topikLevel: 1 },
  { ko: '일자리', en: 'job opening', topikLevel: 2 },
  { ko: '월급', en: 'monthly salary', topikLevel: 1 },
  { ko: '연봉', en: 'annual salary', topikLevel: 2 },
  { ko: '출근', en: 'going to work', topikLevel: 1 },
  { ko: '퇴근', en: 'leaving work', topikLevel: 1 },
  { ko: '회의', en: 'meeting', topikLevel: 1 },
  { ko: '업무', en: 'work / task', topikLevel: 2 },
  { ko: '부장', en: 'department head', topikLevel: 2 },
  { ko: '사장', en: 'CEO / boss', topikLevel: 1 },
  { ko: '직원', en: 'employee', topikLevel: 1 },
  { ko: '의사', en: 'doctor', topikLevel: 1 },
  { ko: '간호사', en: 'nurse', topikLevel: 1 },
  { ko: '경찰', en: 'police officer', topikLevel: 1 },
  { ko: '소방관', en: 'firefighter', topikLevel: 1 },
  { ko: '요리사', en: 'cook / chef', topikLevel: 1 },
  { ko: '운전사', en: 'driver', topikLevel: 1 },
  { ko: '가수', en: 'singer', topikLevel: 1 },
  { ko: '배우', en: 'actor', topikLevel: 1 },
  { ko: '기자', en: 'journalist / reporter', topikLevel: 2 },
  { ko: '변호사', en: 'lawyer', topikLevel: 2 },
  { ko: '작가', en: 'writer / author', topikLevel: 2 },
  { ko: '회사원', en: 'office worker', topikLevel: 1 },
  { ko: '공무원', en: 'civil servant', topikLevel: 2 },
  { ko: '은퇴', en: 'retirement', topikLevel: 2 },
  { ko: '아르바이트', en: 'part-time job', topikLevel: 1 },
  { ko: '면접', en: 'job interview', topikLevel: 2 },

  // ── Hobbies & Leisure ───────────────────────────────────────────────
  { ko: '취미', en: 'hobby', topikLevel: 1 },
  { ko: '여행', en: 'travel', topikLevel: 1 },
  { ko: '영화', en: 'movie / film', topikLevel: 1 },
  { ko: '드라마', en: 'TV drama', topikLevel: 1 },
  { ko: '독서', en: 'reading', topikLevel: 1 },
  { ko: '그림', en: 'drawing / picture', topikLevel: 1 },
  { ko: '사진', en: 'photo', topikLevel: 1 },
  { ko: '노래', en: 'song / singing', topikLevel: 1 },
  { ko: '춤', en: 'dance', topikLevel: 1 },
  { ko: '피아노', en: 'piano', topikLevel: 1 },
  { ko: '기타', en: 'guitar', topikLevel: 1 },
  { ko: '게임', en: 'game', topikLevel: 1 },
  { ko: '인터넷', en: 'internet', topikLevel: 1 },
  { ko: '유튜브', en: 'YouTube', topikLevel: 1 },
  { ko: '소설', en: 'novel', topikLevel: 1 },
  { ko: '만화', en: 'cartoon / comics', topikLevel: 1 },
  { ko: '공연', en: 'performance / show', topikLevel: 2 },
  { ko: '콘서트', en: 'concert', topikLevel: 1 },
  { ko: '전시회', en: 'exhibition', topikLevel: 2 },

  // ── Sports ──────────────────────────────────────────────────────────
  { ko: '운동', en: 'exercise / sport', topikLevel: 1 },
  { ko: '축구', en: 'soccer', topikLevel: 1 },
  { ko: '야구', en: 'baseball', topikLevel: 1 },
  { ko: '농구', en: 'basketball', topikLevel: 1 },
  { ko: '배구', en: 'volleyball', topikLevel: 1 },
  { ko: '수영', en: 'swimming', topikLevel: 1 },
  { ko: '달리기', en: 'running', topikLevel: 1 },
  { ko: '등산', en: 'hiking / mountain climbing', topikLevel: 1 },
  { ko: '테니스', en: 'tennis', topikLevel: 1 },
  { ko: '골프', en: 'golf', topikLevel: 1 },
  { ko: '스키', en: 'skiing', topikLevel: 1 },
  { ko: '태권도', en: 'taekwondo', topikLevel: 1 },
  { ko: '씨름', en: 'Korean wrestling', topikLevel: 2 },
  { ko: '선수', en: 'athlete / player', topikLevel: 1 },
  { ko: '팀', en: 'team', topikLevel: 1 },
  { ko: '경기', en: 'game / match', topikLevel: 1 },
  { ko: '점수', en: 'score', topikLevel: 1 },
  { ko: '승리', en: 'victory', topikLevel: 2 },
  { ko: '패배', en: 'defeat / loss', topikLevel: 2 },

  // ── Technology & Electronics ────────────────────────────────────────
  { ko: '컴퓨터', en: 'computer', topikLevel: 1 },
  { ko: '스마트폰', en: 'smartphone', topikLevel: 1 },
  { ko: '화면', en: 'screen', topikLevel: 1 },
  { ko: '키보드', en: 'keyboard', topikLevel: 1 },
  { ko: '마우스', en: 'computer mouse', topikLevel: 1 },
  { ko: '프린터', en: 'printer', topikLevel: 1 },
  { ko: '카메라', en: 'camera', topikLevel: 1 },
  { ko: '텔레비전', en: 'television', topikLevel: 1 },
  { ko: '라디오', en: 'radio', topikLevel: 1 },
  { ko: '냉장고', en: 'refrigerator', topikLevel: 1 },
  { ko: '세탁기', en: 'washing machine', topikLevel: 1 },
  { ko: '에어컨', en: 'air conditioner', topikLevel: 1 },
  { ko: '전자레인지', en: 'microwave', topikLevel: 1 },
  { ko: '충전기', en: 'charger', topikLevel: 1 },
  { ko: '배터리', en: 'battery', topikLevel: 1 },
  { ko: '비밀번호', en: 'password', topikLevel: 1 },
  { ko: '앱', en: 'app', topikLevel: 1 },
  { ko: '소셜미디어', en: 'social media', topikLevel: 2 },
  { ko: '검색', en: 'search', topikLevel: 1 },
  { ko: '다운로드', en: 'download', topikLevel: 1 },
  { ko: '업로드', en: 'upload', topikLevel: 1 },
  { ko: '와이파이', en: 'Wi-Fi', topikLevel: 1 },
  { ko: '이메일', en: 'email', topikLevel: 1 },

  // ── Animals ─────────────────────────────────────────────────────────
  { ko: '고양이', en: 'cat', topikLevel: 1 },
  { ko: '새', en: 'bird', topikLevel: 1 },
  { ko: '물고기', en: 'fish', topikLevel: 1 },
  { ko: '토끼', en: 'rabbit', topikLevel: 1 },
  { ko: '돼지', en: 'pig', topikLevel: 1 },
  { ko: '소', en: 'cow', topikLevel: 1 },
  { ko: '말', en: 'horse', topikLevel: 1 },
  { ko: '닭', en: 'chicken', topikLevel: 1 },
  { ko: '양', en: 'sheep', topikLevel: 1 },
  { ko: '호랑이', en: 'tiger', topikLevel: 1 },
  { ko: '곰', en: 'bear', topikLevel: 1 },
  { ko: '사자', en: 'lion', topikLevel: 1 },
  { ko: '코끼리', en: 'elephant', topikLevel: 1 },
  { ko: '원숭이', en: 'monkey', topikLevel: 1 },
  { ko: '기린', en: 'giraffe', topikLevel: 1 },
  { ko: '뱀', en: 'snake', topikLevel: 1 },
  { ko: '개구리', en: 'frog', topikLevel: 1 },
  { ko: '나비', en: 'butterfly', topikLevel: 1 },
  { ko: '벌', en: 'bee', topikLevel: 1 },
  { ko: '모기', en: 'mosquito', topikLevel: 1 },
  { ko: '쥐', en: 'mouse / rat', topikLevel: 1 },
  { ko: '여우', en: 'fox', topikLevel: 1 },
  { ko: '늑대', en: 'wolf', topikLevel: 1 },
  { ko: '독수리', en: 'eagle', topikLevel: 2 },
  { ko: '펭귄', en: 'penguin', topikLevel: 1 },
  { ko: '오리', en: 'duck', topikLevel: 1 },
  { ko: '참새', en: 'sparrow', topikLevel: 1 },
  { ko: '까마귀', en: 'crow', topikLevel: 2 },

  // ── Emotions & Feelings ─────────────────────────────────────────────
  { ko: '행복', en: 'happiness', topikLevel: 1 },
  { ko: '슬프다', en: 'sad', topikLevel: 1 },
  { ko: '화가 나다', en: 'angry', topikLevel: 1 },
  { ko: '놀라다', en: 'surprised', topikLevel: 1 },
  { ko: '부끄럽다', en: 'embarrassed', topikLevel: 1 },
  { ko: '외롭다', en: 'lonely', topikLevel: 1 },
  { ko: '걱정', en: 'worry / concern', topikLevel: 1 },
  { ko: '실망', en: 'disappointment', topikLevel: 2 },
  { ko: '기쁨', en: 'joy', topikLevel: 1 },
  { ko: '즐겁다', en: 'enjoyable / fun', topikLevel: 1 },
  { ko: '편하다', en: 'comfortable', topikLevel: 1 },
  { ko: '힘들다', en: 'difficult / hard', topikLevel: 1 },
  { ko: '무섭다', en: 'scary / afraid', topikLevel: 1 },
  { ko: '피곤하다', en: 'tired', topikLevel: 1 },
  { ko: '배고프다', en: 'hungry', topikLevel: 1 },
  { ko: '목마르다', en: 'thirsty', topikLevel: 1 },
  { ko: '졸리다', en: 'sleepy', topikLevel: 1 },
  { ko: '화', en: 'anger', topikLevel: 1 },
  { ko: '기분', en: 'feeling / mood', topikLevel: 1 },
  { ko: '마음', en: 'heart / mind', topikLevel: 1 },
  { ko: '감정', en: 'emotion', topikLevel: 2 },
  { ko: '자신감', en: 'confidence', topikLevel: 2 },
  { ko: '희망', en: 'hope', topikLevel: 1 },
  { ko: '후회', en: 'regret', topikLevel: 2 },
  { ko: '긴장', en: 'tension / nervousness', topikLevel: 2 },
  { ko: '만족', en: 'satisfaction', topikLevel: 2 },

  // ── Colors ──────────────────────────────────────────────────────────
  { ko: '빨간색', en: 'red', topikLevel: 1 },
  { ko: '파란색', en: 'blue', topikLevel: 1 },
  { ko: '노란색', en: 'yellow', topikLevel: 1 },
  { ko: '초록색', en: 'green', topikLevel: 1 },
  { ko: '흰색', en: 'white', topikLevel: 1 },
  { ko: '검은색', en: 'black', topikLevel: 1 },
  { ko: '갈색', en: 'brown', topikLevel: 1 },
  { ko: '회색', en: 'gray', topikLevel: 1 },
  { ko: '주황색', en: 'orange', topikLevel: 1 },
  { ko: '보라색', en: 'purple', topikLevel: 1 },
  { ko: '분홍색', en: 'pink', topikLevel: 1 },
  { ko: '금색', en: 'gold', topikLevel: 1 },
  { ko: '은색', en: 'silver', topikLevel: 1 },
  { ko: '색깔', en: 'color', topikLevel: 1 },
  { ko: '진하다', en: 'dark / thick', topikLevel: 2 },
  { ko: '연하다', en: 'light (color)', topikLevel: 2 },

  // ── Numbers & Quantities ────────────────────────────────────────────
  { ko: '백', en: 'hundred', topikLevel: 1 },
  { ko: '천', en: 'thousand', topikLevel: 1 },
  { ko: '첫째', en: 'first', topikLevel: 1 },
  { ko: '둘째', en: 'second', topikLevel: 1 },
  { ko: '셋째', en: 'third', topikLevel: 1 },
  { ko: '마지막', en: 'last / final', topikLevel: 1 },
  { ko: '많다', en: 'many / much', topikLevel: 1 },
  { ko: '적다', en: 'few / little', topikLevel: 1 },
  { ko: '반', en: 'half', topikLevel: 1 },
  { ko: '전부', en: 'all / everything', topikLevel: 1 },
  { ko: '몇', en: 'how many / several', topikLevel: 1 },
  { ko: '조금', en: 'a little', topikLevel: 1 },
  { ko: '많이', en: 'a lot', topikLevel: 1 },
  { ko: '너무', en: 'too much / too', topikLevel: 1 },
  { ko: '충분히', en: 'enough', topikLevel: 2 },
  { ko: '평균', en: 'average', topikLevel: 2 },

  // ── Common Verbs ────────────────────────────────────────────────────
  { ko: '하다', en: 'do', topikLevel: 1 },
  { ko: '먹다', en: 'eat', topikLevel: 1 },
  { ko: '마시다', en: 'drink', topikLevel: 1 },
  { ko: '보다', en: 'see / watch', topikLevel: 1 },
  { ko: '가다', en: 'go', topikLevel: 1 },
  { ko: '오다', en: 'come', topikLevel: 1 },
  { ko: '있다', en: 'exist / have', topikLevel: 1 },
  { ko: '없다', en: 'not exist / lack', topikLevel: 1 },
  { ko: '되다', en: 'become', topikLevel: 1 },
  { ko: '말하다', en: 'speak / say', topikLevel: 1 },
  { ko: '듣다', en: 'listen / hear', topikLevel: 1 },
  { ko: '읽다', en: 'read', topikLevel: 1 },
  { ko: '쓰다', en: 'write / use', topikLevel: 1 },
  { ko: '앉다', en: 'sit', topikLevel: 1 },
  { ko: '서다', en: 'stand', topikLevel: 1 },
  { ko: '걷다', en: 'walk', topikLevel: 1 },
  { ko: '달리다', en: 'run', topikLevel: 1 },
  { ko: '자다', en: 'sleep', topikLevel: 1 },
  { ko: '일어나다', en: 'wake up / get up', topikLevel: 1 },
  { ko: '사다', en: 'buy', topikLevel: 1 },
  { ko: '팔다', en: 'sell', topikLevel: 1 },
  { ko: '주다', en: 'give', topikLevel: 1 },
  { ko: '받다', en: 'receive', topikLevel: 1 },
  { ko: '열다', en: 'open', topikLevel: 1 },
  { ko: '닫다', en: 'close', topikLevel: 1 },
  { ko: '찾다', en: 'find / look for', topikLevel: 1 },
  { ko: '만들다', en: 'make / create', topikLevel: 1 },
  { ko: '쉬다', en: 'rest', topikLevel: 1 },
  { ko: '놀다', en: 'play / hang out', topikLevel: 1 },
  { ko: '울다', en: 'cry', topikLevel: 1 },
  { ko: '웃다', en: 'laugh / smile', topikLevel: 1 },
  { ko: '죽다', en: 'die', topikLevel: 1 },
  { ko: '살다', en: 'live', topikLevel: 1 },
  { ko: '태어나다', en: 'be born', topikLevel: 1 },
  { ko: '만나다', en: 'meet', topikLevel: 1 },
  { ko: '헤어지다', en: 'break up / part', topikLevel: 2 },
  { ko: '결혼하다', en: 'marry', topikLevel: 1 },
  { ko: '이사하다', en: 'move (residence)', topikLevel: 1 },
  { ko: '이기다', en: 'win', topikLevel: 1 },
  { ko: '지다', en: 'lose', topikLevel: 1 },
  { ko: '넣다', en: 'put in', topikLevel: 1 },
  { ko: '꺼내다', en: 'take out', topikLevel: 1 },
  { ko: '버리다', en: 'throw away', topikLevel: 1 },
  { ko: '고르다', en: 'choose / select', topikLevel: 1 },
  { ko: '기억하다', en: 'remember', topikLevel: 1 },
  { ko: '잊다', en: 'forget', topikLevel: 1 },
  { ko: '모이다', en: 'gather / assemble', topikLevel: 2 },
  { ko: '나누다', en: 'divide / share', topikLevel: 2 },
  { ko: '바꾸다', en: 'change / switch', topikLevel: 1 },
  { ko: '지키다', en: 'keep / protect', topikLevel: 2 },
  { ko: '나타나다', en: 'appear', topikLevel: 2 },
  { ko: '사라지다', en: 'disappear', topikLevel: 2 },
  { ko: '돌아오다', en: 'return / come back', topikLevel: 1 },
  { ko: '내리다', en: 'get off / descend', topikLevel: 1 },
  { ko: '올라가다', en: 'go up', topikLevel: 1 },
  { ko: '내려가다', en: 'go down', topikLevel: 1 },
  { ko: '들어가다', en: 'go in / enter', topikLevel: 1 },
  { ko: '나오다', en: 'come out', topikLevel: 1 },
  { ko: '지나가다', en: 'pass by', topikLevel: 1 },
  { ko: '돌다', en: 'turn / rotate', topikLevel: 1 },
  { ko: '떠나다', en: 'leave / depart', topikLevel: 1 },
  { ko: '도착하다', en: 'arrive', topikLevel: 1 },
  { ko: '출발하다', en: 'depart / set off', topikLevel: 1 },
  { ko: '예약하다', en: 'reserve / book', topikLevel: 1 },
  { ko: '계획하다', en: 'plan', topikLevel: 1 },
  { ko: '신청하다', en: 'apply / sign up', topikLevel: 2 },
  { ko: '연락하다', en: 'contact', topikLevel: 1 },
  { ko: '이야기하다', en: 'talk / tell', topikLevel: 1 },
  { ko: '묻다', en: 'ask', topikLevel: 1 },
  { ko: '대답하다', en: 'answer / reply', topikLevel: 1 },
  { ko: '설명하다', en: 'explain', topikLevel: 1 },
  { ko: '소개하다', en: 'introduce', topikLevel: 1 },
  { ko: '생각하다', en: 'think', topikLevel: 1 },
  { ko: '알다', en: 'know', topikLevel: 1 },
  { ko: '모르다', en: 'not know', topikLevel: 1 },
  { ko: '배우다', en: 'learn', topikLevel: 1 },
  { ko: '가르치다', en: 'teach', topikLevel: 1 },
  { ko: '노력하다', en: 'make an effort', topikLevel: 2 },
  { ko: '결정하다', en: 'decide', topikLevel: 2 },
  { ko: '시작하다', en: 'start / begin', topikLevel: 1 },
  { ko: '끝나다', en: 'end / finish', topikLevel: 1 },
  { ko: '끝내다', en: 'finish (something)', topikLevel: 1 },
  { ko: '계속하다', en: 'continue', topikLevel: 1 },
  { ko: '멈추다', en: 'stop', topikLevel: 1 },
  { ko: '보내다', en: 'send / spend (time)', topikLevel: 1 },
  { ko: '가져오다', en: 'bring', topikLevel: 1 },
  { ko: '가져가다', en: 'take away', topikLevel: 1 },
  { ko: '올리다', en: 'upload / raise', topikLevel: 1 },
  { ko: '내다', en: 'pay / submit', topikLevel: 1 },
  { ko: '고치다', en: 'fix / repair', topikLevel: 1 },
  { ko: '청소하다', en: 'clean', topikLevel: 1 },
  { ko: '요리하다', en: 'cook', topikLevel: 1 },
  { ko: '전화하다', en: 'call (phone)', topikLevel: 1 },
  { ko: '약속하다', en: 'promise', topikLevel: 1 },
  { ko: '초대하다', en: 'invite', topikLevel: 1 },
  { ko: '방문하다', en: 'visit', topikLevel: 1 },
  { ko: '참가하다', en: 'participate', topikLevel: 2 },
  { ko: '졸업하다', en: 'graduate', topikLevel: 1 },
  { ko: '취직하다', en: 'get a job', topikLevel: 2 },
  { ko: '운전하다', en: 'drive', topikLevel: 1 },
  { ko: '타다', en: 'ride / board', topikLevel: 1 },

  // ── Common Adjectives ───────────────────────────────────────────────
  { ko: '크다', en: 'big', topikLevel: 1 },
  { ko: '작다', en: 'small', topikLevel: 1 },
  { ko: '길다', en: 'long', topikLevel: 1 },
  { ko: '짧다', en: 'short', topikLevel: 1 },
  { ko: '높다', en: 'high / tall', topikLevel: 1 },
  { ko: '낮다', en: 'low', topikLevel: 1 },
  { ko: '넓다', en: 'wide / spacious', topikLevel: 1 },
  { ko: '좁다', en: 'narrow', topikLevel: 1 },
  { ko: '깊다', en: 'deep', topikLevel: 1 },
  { ko: '얕다', en: 'shallow', topikLevel: 2 },
  { ko: '무겁다', en: 'heavy', topikLevel: 1 },
  { ko: '가볍다', en: 'light (weight)', topikLevel: 1 },
  { ko: '빠르다', en: 'fast / quick', topikLevel: 1 },
  { ko: '느리다', en: 'slow', topikLevel: 1 },
  { ko: '뜨겁다', en: 'hot (touch)', topikLevel: 1 },
  { ko: '차갑다', en: 'cold (touch)', topikLevel: 1 },
  { ko: '따뜻하다', en: 'warm', topikLevel: 1 },
  { ko: '시원하다', en: 'cool / refreshing', topikLevel: 1 },
  { ko: '맛있다', en: 'delicious', topikLevel: 1 },
  { ko: '맛없다', en: 'tasteless / bad', topikLevel: 1 },
  { ko: '달다', en: 'sweet', topikLevel: 1 },
  { ko: '맵다', en: 'spicy', topikLevel: 1 },
  { ko: '짜다', en: 'salty', topikLevel: 1 },
  { ko: '씁쓸하다', en: 'bitter / bittersweet', topikLevel: 2 },
  { ko: '시다', en: 'sour', topikLevel: 1 },
  { ko: '새롭다', en: 'new', topikLevel: 1 },
  { ko: '오래되다', en: 'old / aged', topikLevel: 1 },
  { ko: '깨끗하다', en: 'clean', topikLevel: 1 },
  { ko: '더럽다', en: 'dirty', topikLevel: 1 },
  { ko: '밝다', en: 'bright', topikLevel: 1 },
  { ko: '어둡다', en: 'dark', topikLevel: 1 },
  { ko: '조용하다', en: 'quiet', topikLevel: 1 },
  { ko: '시끄럽다', en: 'noisy', topikLevel: 1 },
  { ko: '바쁘다', en: 'busy', topikLevel: 1 },
  { ko: '한가하다', en: 'free / not busy', topikLevel: 1 },
  { ko: '쉽다', en: 'easy', topikLevel: 1 },
  { ko: '어렵다', en: 'difficult', topikLevel: 1 },
  { ko: '중요하다', en: 'important', topikLevel: 1 },
  { ko: '필요하다', en: 'necessary', topikLevel: 1 },
  { ko: '가능하다', en: 'possible', topikLevel: 2 },
  { ko: '불가능하다', en: 'impossible', topikLevel: 2 },
  { ko: '비슷하다', en: 'similar', topikLevel: 2 },
  { ko: '같다', en: 'same', topikLevel: 1 },
  { ko: '다르다', en: 'different', topikLevel: 1 },
  { ko: '좋다', en: 'good', topikLevel: 1 },
  { ko: '나쁘다', en: 'bad', topikLevel: 1 },
  { ko: '이상하다', en: 'strange / weird', topikLevel: 1 },
  { ko: '재미없다', en: 'boring', topikLevel: 1 },
  { ko: '건강하다', en: 'healthy', topikLevel: 1 },

  // ── Greetings & Etiquette ───────────────────────────────────────────
  { ko: '감사합니다', en: 'thank you', topikLevel: 1 },
  { ko: '죄송합니다', en: 'I am sorry', topikLevel: 1 },
  { ko: '실례합니다', en: 'excuse me', topikLevel: 1 },
  { ko: '괜찮아요', en: 'it is okay', topikLevel: 1 },
  { ko: '반갑습니다', en: 'nice to meet you', topikLevel: 1 },
  { ko: '처음', en: 'first time / beginning', topikLevel: 1 },
  { ko: '수고하다', en: 'work hard', topikLevel: 1 },
  { ko: '화이팅', en: 'fighting / go for it', topikLevel: 1 },
  { ko: '잠깐만요', en: 'just a moment', topikLevel: 1 },
  { ko: '어서오세요', en: 'welcome', topikLevel: 1 },

  // ── Directions ──────────────────────────────────────────────────────
  { ko: '위', en: 'above / top', topikLevel: 1 },
  { ko: '아래', en: 'below / bottom', topikLevel: 1 },
  { ko: '왼쪽', en: 'left side', topikLevel: 1 },
  { ko: '오른쪽', en: 'right side', topikLevel: 1 },
  { ko: '앞', en: 'front', topikLevel: 1 },
  { ko: '뒤', en: 'back / behind', topikLevel: 1 },
  { ko: '옆', en: 'side / next to', topikLevel: 1 },
  { ko: '안', en: 'inside', topikLevel: 1 },
  { ko: '밖', en: 'outside', topikLevel: 1 },
  { ko: '사이', en: 'between', topikLevel: 1 },
  { ko: '근처', en: 'nearby', topikLevel: 1 },
  { ko: '멀리', en: 'far away', topikLevel: 1 },
  { ko: '가까이', en: 'nearby / close', topikLevel: 1 },
  { ko: '동쪽', en: 'east', topikLevel: 1 },
  { ko: '서쪽', en: 'west', topikLevel: 1 },
  { ko: '남쪽', en: 'south', topikLevel: 1 },
  { ko: '북쪽', en: 'north', topikLevel: 1 },
  { ko: '직진', en: 'go straight', topikLevel: 1 },
  { ko: '모퉁이', en: 'corner', topikLevel: 2 },

  // ── Household ───────────────────────────────────────────────────────
  { ko: '방', en: 'room', topikLevel: 1 },
  { ko: '부엌', en: 'kitchen', topikLevel: 1 },
  { ko: '거실', en: 'living room', topikLevel: 1 },
  { ko: '침실', en: 'bedroom', topikLevel: 1 },
  { ko: '욕실', en: 'bathroom', topikLevel: 1 },
  { ko: '창문', en: 'window', topikLevel: 1 },
  { ko: '천장', en: 'ceiling', topikLevel: 1 },
  { ko: '바닥', en: 'floor', topikLevel: 1 },
  { ko: '벽', en: 'wall', topikLevel: 1 },
  { ko: '지붕', en: 'roof', topikLevel: 1 },
  { ko: '가구', en: 'furniture', topikLevel: 1 },
  { ko: '책상', en: 'desk', topikLevel: 1 },
  { ko: '침대', en: 'bed', topikLevel: 1 },
  { ko: '소파', en: 'sofa', topikLevel: 1 },
  { ko: '의자', en: 'chair', topikLevel: 1 },
  { ko: '식탁', en: 'dining table', topikLevel: 1 },
  { ko: '그릇', en: 'bowl / dish', topikLevel: 1 },
  { ko: '컵', en: 'cup', topikLevel: 1 },
  { ko: '젓가락', en: 'chopsticks', topikLevel: 1 },
  { ko: '숟가락', en: 'spoon', topikLevel: 1 },
  { ko: '냄비', en: 'pot', topikLevel: 1 },
  { ko: '프라이팬', en: 'frying pan', topikLevel: 1 },
  { ko: '쓰레기', en: 'trash / garbage', topikLevel: 1 },
  { ko: '비누', en: 'soap', topikLevel: 1 },
  { ko: '치약', en: 'toothpaste', topikLevel: 1 },
  { ko: '칫솔', en: 'toothbrush', topikLevel: 1 },
  { ko: '수건', en: 'towel', topikLevel: 1 },
  { ko: '이불', en: 'blanket', topikLevel: 1 },
  { ko: '베개', en: 'pillow', topikLevel: 1 },

  // ── Clothing ────────────────────────────────────────────────────────
  { ko: '바지', en: 'pants / trousers', topikLevel: 1 },
  { ko: '치마', en: 'skirt', topikLevel: 1 },
  { ko: '셔츠', en: 'shirt', topikLevel: 1 },
  { ko: '티셔츠', en: 'T-shirt', topikLevel: 1 },
  { ko: '재킷', en: 'jacket', topikLevel: 1 },
  { ko: '코트', en: 'coat', topikLevel: 1 },
  { ko: '원피스', en: 'dress', topikLevel: 1 },
  { ko: '양말', en: 'socks', topikLevel: 1 },
  { ko: '신발', en: 'shoes', topikLevel: 1 },
  { ko: '운동화', en: 'sneakers', topikLevel: 1 },
  { ko: '구두', en: 'formal shoes', topikLevel: 1 },
  { ko: '모자', en: 'hat / cap', topikLevel: 1 },
  { ko: '장갑', en: 'gloves', topikLevel: 1 },
  { ko: '목도리', en: 'scarf', topikLevel: 1 },
  { ko: '넥타이', en: 'necktie', topikLevel: 1 },
  { ko: '청바지', en: 'jeans', topikLevel: 1 },
  { ko: '속옷', en: 'underwear', topikLevel: 1 },
  { ko: '한복', en: 'traditional Korean clothing', topikLevel: 1 },
  { ko: '입다', en: 'wear (clothing)', topikLevel: 1 },
  { ko: '벗다', en: 'take off (clothing)', topikLevel: 1 },

  // ── Health & Illness ────────────────────────────────────────────────
  { ko: '건강', en: 'health', topikLevel: 1 },
  { ko: '아프다', en: 'hurt / sick', topikLevel: 1 },
  { ko: '감기', en: 'cold (illness)', topikLevel: 1 },
  { ko: '열', en: 'fever', topikLevel: 1 },
  { ko: '기침', en: 'cough', topikLevel: 1 },
  { ko: '두통', en: 'headache', topikLevel: 1 },
  { ko: '복통', en: 'stomachache', topikLevel: 1 },
  { ko: '약', en: 'medicine', topikLevel: 1 },
  { ko: '주사', en: 'injection / shot', topikLevel: 1 },
  { ko: '수술', en: 'surgery / operation', topikLevel: 2 },
  { ko: '상처', en: 'wound / injury', topikLevel: 1 },
  { ko: '혈액', en: 'blood', topikLevel: 2 },
  { ko: '피', en: 'blood', topikLevel: 1 },
  { ko: '진료', en: 'medical treatment', topikLevel: 2 },
  { ko: '처방', en: 'prescription', topikLevel: 2 },
  { ko: '입원', en: 'hospitalization', topikLevel: 2 },
  { ko: '퇴원', en: 'discharge from hospital', topikLevel: 2 },
  { ko: '다이어트', en: 'diet', topikLevel: 1 },
  { ko: '알레르기', en: 'allergy', topikLevel: 2 },
  { ko: '치료', en: 'treatment / cure', topikLevel: 2 },

  // ── Government & Society ────────────────────────────────────────────
  { ko: '정부', en: 'government', topikLevel: 2 },
  { ko: '법', en: 'law', topikLevel: 2 },
  { ko: '사회', en: 'society', topikLevel: 2 },
  { ko: '문화', en: 'culture', topikLevel: 1 },
  { ko: '경제', en: 'economy', topikLevel: 2 },
  { ko: '환경', en: 'environment', topikLevel: 2 },
  { ko: '교육', en: 'education', topikLevel: 1 },
  { ko: '인구', en: 'population', topikLevel: 2 },
  { ko: '뉴스', en: 'news', topikLevel: 1 },
  { ko: '신문', en: 'newspaper', topikLevel: 1 },
  { ko: '방송', en: 'broadcast', topikLevel: 2 },
  { ko: '광고', en: 'advertisement', topikLevel: 1 },
  { ko: '선거', en: 'election', topikLevel: 2 },
  { ko: '대통령', en: 'president', topikLevel: 1 },
  { ko: '시민', en: 'citizen', topikLevel: 2 },
  { ko: '국민', en: 'people / nation', topikLevel: 2 },
  { ko: '세금', en: 'tax', topikLevel: 2 },
  { ko: '복지', en: 'welfare', topikLevel: 2 },
  { ko: '역할', en: 'role', topikLevel: 2 },
  { ko: '문제', en: 'problem / issue', topikLevel: 1 },
  { ko: '해결', en: 'solution / resolution', topikLevel: 2 },

  // ── Common Nouns (miscellaneous) ────────────────────────────────────
  { ko: '것', en: 'thing', topikLevel: 1 },
  { ko: '때', en: 'time / when', topikLevel: 1 },
  { ko: '곳', en: 'place', topikLevel: 1 },
  { ko: '방법', en: 'method / way', topikLevel: 1 },
  { ko: '이유', en: 'reason', topikLevel: 1 },
  { ko: '결과', en: 'result', topikLevel: 2 },
  { ko: '경험', en: 'experience', topikLevel: 2 },
  { ko: '기회', en: 'opportunity', topikLevel: 2 },
  { ko: '목표', en: 'goal / target', topikLevel: 2 },
  { ko: '계획', en: 'plan', topikLevel: 1 },
  { ko: '약속', en: 'promise / appointment', topikLevel: 1 },
  { ko: '조건', en: 'condition', topikLevel: 2 },
  { ko: '관계', en: 'relationship', topikLevel: 2 },
  { ko: '차이', en: 'difference', topikLevel: 2 },
  { ko: '정도', en: 'degree / extent', topikLevel: 1 },
  { ko: '종류', en: 'type / kind', topikLevel: 1 },
  { ko: '내용', en: 'content', topikLevel: 2 },
  { ko: '제목', en: 'title', topikLevel: 1 },
  { ko: '주제', en: 'topic / theme', topikLevel: 2 },
  { ko: '이야기', en: 'story / talk', topikLevel: 1 },
  { ko: '질문', en: 'question', topikLevel: 1 },
  { ko: '대답', en: 'answer', topikLevel: 1 },
  { ko: '의미', en: 'meaning', topikLevel: 1 },
  { ko: '생각', en: 'thought / idea', topikLevel: 1 },
  { ko: '의견', en: 'opinion', topikLevel: 2 },
  { ko: '느낌', en: 'feeling', topikLevel: 1 },
  { ko: '모습', en: 'appearance', topikLevel: 2 },
  { ko: '부분', en: 'part', topikLevel: 1 },
  { ko: '전체', en: 'whole / entire', topikLevel: 2 },
  { ko: '중간', en: 'middle / center', topikLevel: 1 },
  { ko: '끝', en: 'end', topikLevel: 1 },
  { ko: '시작', en: 'start / beginning', topikLevel: 1 },
  { ko: '과정', en: 'process', topikLevel: 2 },
  { ko: '규칙', en: 'rule', topikLevel: 2 },
  { ko: '순서', en: 'order / sequence', topikLevel: 2 },
  { ko: '준비물', en: 'supplies / materials', topikLevel: 2 },
  { ko: '정보', en: 'information', topikLevel: 1 },
  { ko: '자료', en: 'data / material', topikLevel: 2 },
  { ko: '연구', en: 'research', topikLevel: 2 },
  { ko: '발전', en: 'development / progress', topikLevel: 2 },
  { ko: '변화', en: 'change', topikLevel: 2 },
  { ko: '영향', en: 'influence / effect', topikLevel: 2 },

  // ── Common Adverbs & Function Words ────────────────────────────────
  { ko: '왜냐하면', en: 'because', topikLevel: 1 },
  { ko: '그래서', en: 'therefore / so', topikLevel: 1 },
  { ko: '그런데', en: 'but / by the way', topikLevel: 1 },
  { ko: '그리고', en: 'and / also', topikLevel: 1 },
  { ko: '하지만', en: 'but / however', topikLevel: 1 },
  { ko: '그러나', en: 'however', topikLevel: 1 },
  { ko: '또한', en: 'also / furthermore', topikLevel: 2 },
  { ko: '특히', en: 'especially', topikLevel: 2 },
  { ko: '주로', en: 'mainly', topikLevel: 2 },
  { ko: '정말', en: 'really / truly', topikLevel: 1 },
  { ko: '매우', en: 'very', topikLevel: 1 },
  { ko: '아마', en: 'probably', topikLevel: 1 },
  { ko: '잘', en: 'well', topikLevel: 1 },
  { ko: '모두', en: 'all / everyone', topikLevel: 1 },
  { ko: '함께', en: 'together', topikLevel: 1 },
  { ko: '혼자', en: 'alone', topikLevel: 1 },
  { ko: '같이', en: 'together', topikLevel: 1 },
  { ko: '바로', en: 'right / immediately', topikLevel: 1 },
  { ko: '다시', en: 'again', topikLevel: 1 },
  { ko: '더', en: 'more', topikLevel: 1 },
  { ko: '덜', en: 'less', topikLevel: 1 },
  { ko: '빨리', en: 'quickly', topikLevel: 1 },
  { ko: '느리게', en: 'slowly', topikLevel: 1 },
  { ko: '이렇게', en: 'like this', topikLevel: 1 },
  { ko: '저렇게', en: 'like that', topikLevel: 1 },
  { ko: '어떻게', en: 'how / in what way', topikLevel: 1 },
  { ko: '왜', en: 'why', topikLevel: 1 },
  { ko: '무엇', en: 'what', topikLevel: 1 },
  { ko: '누가', en: 'who', topikLevel: 1 },
  { ko: '어디서', en: 'where (from)', topikLevel: 1 },
  { ko: '얼마나', en: 'how much / how many', topikLevel: 1 },
  { ko: '언제쯤', en: 'around when', topikLevel: 2 },
  { ko: '하루에', en: 'per day', topikLevel: 1 },

  // ── Academic & Abstract ─────────────────────────────────────────────
  { ko: '수', en: 'number / count', topikLevel: 1 },
  { ko: '크기', en: 'size', topikLevel: 1 },
  { ko: '무게', en: 'weight', topikLevel: 1 },
  { ko: '속도', en: 'speed', topikLevel: 2 },
  { ko: '방향', en: 'direction', topikLevel: 1 },
  { ko: '모양', en: 'shape / form', topikLevel: 1 },
  { ko: '색', en: 'color', topikLevel: 1 },
  { ko: '지식', en: 'knowledge', topikLevel: 2 },
  { ko: '능력', en: 'ability / skill', topikLevel: 2 },
  { ko: '실력', en: 'ability / proficiency', topikLevel: 2 },
  { ko: '태도', en: 'attitude', topikLevel: 2 },
  { ko: '성격', en: 'personality', topikLevel: 1 },
  { ko: '가치', en: 'value / worth', topikLevel: 2 },
  { ko: '목적', en: 'purpose', topikLevel: 2 },
  { ko: '원인', en: 'cause / reason', topikLevel: 2 },
  { ko: '특징', en: 'characteristic', topikLevel: 2 },
  { ko: '장점', en: 'advantage / strength', topikLevel: 2 },
  { ko: '단점', en: 'disadvantage / weakness', topikLevel: 2 },
  { ko: '형태', en: 'form / shape', topikLevel: 2 },
  { ko: '상황', en: 'situation', topikLevel: 2 },
  { ko: '현재', en: 'present / now', topikLevel: 2 },
  { ko: '과거', en: 'past', topikLevel: 2 },
  { ko: '미래', en: 'future', topikLevel: 1 },
  { ko: '세계', en: 'world', topikLevel: 1 },

  // ── More People & Social ────────────────────────────────────────────
  { ko: '인간', en: 'human being', topikLevel: 2 },
  { ko: '개인', en: 'individual', topikLevel: 2 },
  { ko: '집단', en: 'group', topikLevel: 2 },
  { ko: '팬', en: 'fan', topikLevel: 1 },
  { ko: '손님', en: 'guest / customer', topikLevel: 1 },
  { ko: '주인', en: 'owner / host', topikLevel: 1 },
  { ko: '동료', en: 'colleague', topikLevel: 2 },
  { ko: '파트너', en: 'partner', topikLevel: 2 },
  { ko: '연인', en: 'lover / couple', topikLevel: 2 },
  { ko: '상대방', en: 'the other party', topikLevel: 2 },

  // ── More Body & Health ──────────────────────────────────────────────
  { ko: '심장', en: 'heart (organ)', topikLevel: 2 },
  { ko: '폐', en: 'lung', topikLevel: 2 },
  { ko: '뇌', en: 'brain', topikLevel: 2 },
  { ko: '신장', en: 'kidney', topikLevel: 2 },
  { ko: '근육', en: 'muscle', topikLevel: 2 },
  { ko: '체중', en: 'body weight', topikLevel: 1 },
  { ko: '키', en: 'height', topikLevel: 1 },
  { ko: '나이', en: 'age', topikLevel: 1 },
  { ko: '혈압', en: 'blood pressure', topikLevel: 2 },
  { ko: '당뇨', en: 'diabetes', topikLevel: 2 },
  { ko: '독감', en: 'flu / influenza', topikLevel: 1 },
  { ko: '소화', en: 'digestion', topikLevel: 2 },
  { ko: '면역', en: 'immunity', topikLevel: 2 },

  // ── More Food ───────────────────────────────────────────────────────
  { ko: '두부', en: 'tofu', topikLevel: 1 },
  { ko: '된장', en: 'soybean paste', topikLevel: 1 },
  { ko: '고추장', en: 'red pepper paste', topikLevel: 1 },
  { ko: '참기름', en: 'sesame oil', topikLevel: 1 },
  { ko: '깨', en: 'sesame seed', topikLevel: 1 },
  { ko: '파', en: 'green onion', topikLevel: 1 },
  { ko: '시금치', en: 'spinach', topikLevel: 1 },
  { ko: '버섯', en: 'mushroom', topikLevel: 1 },
  { ko: '오이', en: 'cucumber', topikLevel: 1 },
  { ko: '토마토', en: 'tomato', topikLevel: 1 },
  { ko: '사탕', en: 'candy', topikLevel: 1 },
  { ko: '빵집', en: 'bakery', topikLevel: 1 },
  { ko: '포크', en: 'fork', topikLevel: 1 },
  { ko: '칼', en: 'knife', topikLevel: 1 },

  // ── More Time ───────────────────────────────────────────────────────
  { ko: '평일', en: 'weekday', topikLevel: 1 },
  { ko: '공휴일', en: 'public holiday', topikLevel: 1 },
  { ko: '생일', en: 'birthday', topikLevel: 1 },
  { ko: '기념일', en: 'anniversary', topikLevel: 1 },
  { ko: '명절', en: 'traditional holiday', topikLevel: 1 },
  { ko: '추석', en: 'Chuseok', topikLevel: 1 },
  { ko: '설날', en: 'Lunar New Year', topikLevel: 1 },
  { ko: '크리스마스', en: 'Christmas', topikLevel: 1 },
  { ko: '세기', en: 'century', topikLevel: 2 },
  { ko: '시대', en: 'era / age', topikLevel: 2 },

  // ── More Places ─────────────────────────────────────────────────────
  { ko: '제주도', en: 'Jeju Island', topikLevel: 1 },
  { ko: '섬', en: 'island', topikLevel: 1 },
  { ko: '사막', en: 'desert', topikLevel: 2 },
  { ko: '동굴', en: 'cave', topikLevel: 2 },
  { ko: '폭포', en: 'waterfall', topikLevel: 2 },
  { ko: '항구', en: 'harbor / port', topikLevel: 2 },
  { ko: '터널', en: 'tunnel', topikLevel: 1 },
  { ko: '교량', en: 'bridge', topikLevel: 2 },
  { ko: '공장', en: 'factory', topikLevel: 2 },
  { ko: '농장', en: 'farm', topikLevel: 1 },
  { ko: '학원', en: 'private academy', topikLevel: 1 },
  { ko: '헬스장', en: 'gym / fitness center', topikLevel: 1 },
  { ko: '노래방', en: 'karaoke room', topikLevel: 1 },
  { ko: '찜질방', en: 'Korean sauna', topikLevel: 1 },

  // ── More Transportation ─────────────────────────────────────────────
  { ko: '고속도로', en: 'highway / expressway', topikLevel: 1 },
  { ko: '인도', en: 'sidewalk / India', topikLevel: 1 },
  { ko: '횡단보도', en: 'crosswalk', topikLevel: 1 },
  { ko: '속력', en: 'speed', topikLevel: 2 },
  { ko: '연착', en: 'delay (transport)', topikLevel: 2 },
  { ko: '환승', en: 'transfer (transit)', topikLevel: 1 },

  // ── More Shopping ───────────────────────────────────────────────────
  { ko: '무료', en: 'free (no charge)', topikLevel: 1 },
  { ko: '유료', en: 'paid / charged', topikLevel: 2 },
  { ko: '품질', en: 'quality', topikLevel: 2 },
  { ko: '신제품', en: 'new product', topikLevel: 2 },
  { ko: '중고', en: 'secondhand / used', topikLevel: 1 },
  { ko: '배달', en: 'delivery', topikLevel: 1 },

  // ── More School & Learning ──────────────────────────────────────────
  { ko: '강의', en: 'lecture', topikLevel: 2 },
  { ko: '발표', en: 'presentation', topikLevel: 1 },
  { ko: '토론', en: 'debate / discussion', topikLevel: 2 },
  { ko: '논문', en: 'thesis / paper', topikLevel: 2 },
  { ko: '전공', en: 'major (academic)', topikLevel: 2 },
  { ko: '장학금', en: 'scholarship', topikLevel: 2 },
  { ko: '교수', en: 'professor', topikLevel: 1 },
  { ko: '교장', en: 'school principal', topikLevel: 2 },
  { ko: '유치원', en: 'kindergarten', topikLevel: 1 },

  // ── More Work ───────────────────────────────────────────────────────
  { ko: '야근', en: 'overtime / late night work', topikLevel: 2 },
  { ko: '휴가', en: 'vacation / leave', topikLevel: 1 },
  { ko: '출장', en: 'business trip', topikLevel: 2 },
  { ko: '계약', en: 'contract', topikLevel: 2 },
  { ko: '프로젝트', en: 'project', topikLevel: 1 },
  { ko: '마감', en: 'deadline', topikLevel: 2 },
  { ko: '성과', en: 'achievement / result', topikLevel: 2 },
  { ko: '승진', en: 'promotion', topikLevel: 2 },
  { ko: '건축가', en: 'architect', topikLevel: 2 },
  { ko: '디자이너', en: 'designer', topikLevel: 1 },
  { ko: '프로그래머', en: 'programmer', topikLevel: 1 },

  // ── More Emotions ───────────────────────────────────────────────────
  { ko: '설레다', en: 'excited / thrilled', topikLevel: 2 },
  { ko: '그립다', en: 'miss / long for', topikLevel: 2 },
  { ko: '답답하다', en: 'frustrated / stuffy', topikLevel: 2 },
  { ko: '억울하다', en: 'unfairly treated', topikLevel: 2 },
  { ko: '부럽다', en: 'envious / jealous', topikLevel: 1 },
  { ko: '무관심', en: 'indifference', topikLevel: 2 },
  { ko: '열정', en: 'passion', topikLevel: 2 },
  { ko: '용기', en: 'courage', topikLevel: 1 },
  { ko: '인내', en: 'patience / endurance', topikLevel: 2 },
  { ko: '자존심', en: 'pride / self-respect', topikLevel: 2 },

  // ── More Adjectives ─────────────────────────────────────────────────
  { ko: '둥글다', en: 'round', topikLevel: 1 },
  { ko: '네모나다', en: 'square / rectangular', topikLevel: 1 },
  { ko: '날카롭다', en: 'sharp', topikLevel: 2 },
  { ko: '부드럽다', en: 'soft / gentle', topikLevel: 1 },
  { ko: '딱딱하다', en: 'hard / stiff', topikLevel: 1 },
  { ko: '촉촉하다', en: 'moist / damp', topikLevel: 2 },
  { ko: '건조하다', en: 'dry', topikLevel: 2 },
  { ko: '무딘', en: 'blunt / dull', topikLevel: 2 },
  { ko: '두껍다', en: 'thick', topikLevel: 1 },
  { ko: '얇다', en: 'thin', topikLevel: 1 },
  { ko: '복잡하다', en: 'complicated / crowded', topikLevel: 1 },
  { ko: '단순하다', en: 'simple', topikLevel: 2 },
  { ko: '정확하다', en: 'accurate / exact', topikLevel: 2 },
  { ko: '틀리다', en: 'wrong / incorrect', topikLevel: 1 },
  { ko: '맞다', en: 'correct / right', topikLevel: 1 },
  { ko: '유명하다', en: 'famous', topikLevel: 1 },
  { ko: '인기 있다', en: 'popular', topikLevel: 1 },
  { ko: '특별하다', en: 'special', topikLevel: 1 },
  { ko: '평범하다', en: 'ordinary / common', topikLevel: 2 },
  { ko: '다양하다', en: 'diverse / various', topikLevel: 2 },

  // ── More Verbs ──────────────────────────────────────────────────────
  { ko: '느끼다', en: 'feel / sense', topikLevel: 1 },
  { ko: '원하다', en: 'want', topikLevel: 1 },
  { ko: '바라다', en: 'hope / wish', topikLevel: 1 },
  { ko: '믿다', en: 'believe / trust', topikLevel: 1 },
  { ko: '이해하다', en: 'understand', topikLevel: 1 },
  { ko: '확인하다', en: 'check / confirm', topikLevel: 1 },
  { ko: '비교하다', en: 'compare', topikLevel: 2 },
  { ko: '선택하다', en: 'choose / select', topikLevel: 1 },
  { ko: '포기하다', en: 'give up', topikLevel: 1 },
  { ko: '도전하다', en: 'challenge / try', topikLevel: 2 },
  { ko: '성공하다', en: 'succeed', topikLevel: 1 },
  { ko: '실패하다', en: 'fail', topikLevel: 1 },
  { ko: '참다', en: 'endure / hold back', topikLevel: 1 },
  { ko: '도망가다', en: 'run away / flee', topikLevel: 1 },
  { ko: '싸우다', en: 'fight / argue', topikLevel: 1 },
  { ko: '화해하다', en: 'reconcile / make up', topikLevel: 2 },
  { ko: '부탁하다', en: 'ask a favor', topikLevel: 1 },
  { ko: '허락하다', en: 'allow / permit', topikLevel: 2 },
  { ko: '거절하다', en: 'refuse / decline', topikLevel: 2 },
  { ko: '반복하다', en: 'repeat', topikLevel: 2 },
  { ko: '표현하다', en: 'express', topikLevel: 2 },
  { ko: '공유하다', en: 'share', topikLevel: 2 },
  { ko: '참여하다', en: 'participate', topikLevel: 2 },
  { ko: '돌보다', en: 'take care of', topikLevel: 1 },
  { ko: '걱정하다', en: 'worry', topikLevel: 1 },
  { ko: '따라가다', en: 'follow', topikLevel: 1 },
  { ko: '당기다', en: 'pull', topikLevel: 1 },
  { ko: '밀다', en: 'push', topikLevel: 1 },
  { ko: '잡다', en: 'grab / hold', topikLevel: 1 },
  { ko: '놓다', en: 'put down / let go', topikLevel: 1 },
  { ko: '던지다', en: 'throw', topikLevel: 1 },
  { ko: '치다', en: 'hit / strike', topikLevel: 1 },
  { ko: '쌓다', en: 'pile up / stack', topikLevel: 2 },
  { ko: '줄다', en: 'decrease / shrink', topikLevel: 2 },
  { ko: '늘다', en: 'increase / grow', topikLevel: 1 },
  { ko: '섞다', en: 'mix', topikLevel: 2 },
  { ko: '자르다', en: 'cut', topikLevel: 1 },
  { ko: '붙이다', en: 'attach / stick', topikLevel: 1 },
  { ko: '지우다', en: 'erase / delete', topikLevel: 1 },
  { ko: '켜다', en: 'turn on', topikLevel: 1 },
  { ko: '끄다', en: 'turn off', topikLevel: 1 },
  { ko: '빌리다', en: 'borrow / lend', topikLevel: 1 },
  { ko: '갚다', en: 'pay back / repay', topikLevel: 2 },
  { ko: '응원하다', en: 'cheer / support', topikLevel: 1 },

  // ── More Nature & Environment ───────────────────────────────────────
  { ko: '태양', en: 'sun / solar', topikLevel: 1 },
  { ko: '지구', en: 'Earth', topikLevel: 1 },
  { ko: '우주', en: 'universe / space', topikLevel: 1 },
  { ko: '행성', en: 'planet', topikLevel: 2 },
  { ko: '화산', en: 'volcano', topikLevel: 2 },
  { ko: '지진', en: 'earthquake', topikLevel: 2 },
  { ko: '파도', en: 'wave (ocean)', topikLevel: 1 },
  { ko: '모래', en: 'sand', topikLevel: 1 },
  { ko: '흙', en: 'soil / dirt', topikLevel: 1 },
  { ko: '씨앗', en: 'seed', topikLevel: 1 },
  { ko: '뿌리', en: 'root', topikLevel: 2 },
  { ko: '가지', en: 'branch', topikLevel: 1 },

  // ── More Society & Abstract ─────────────────────────────────────────
  { ko: '전통', en: 'tradition', topikLevel: 2 },
  { ko: '현대', en: 'modern / contemporary', topikLevel: 2 },
  { ko: '언어', en: 'language', topikLevel: 1 },
  { ko: '외국어', en: 'foreign language', topikLevel: 1 },
  { ko: '통역', en: 'interpretation', topikLevel: 2 },
  { ko: '번역', en: 'translation', topikLevel: 2 },
  { ko: '여론', en: 'public opinion', topikLevel: 2 },
  { ko: '차별', en: 'discrimination', topikLevel: 2 },
  { ko: '평등', en: 'equality', topikLevel: 2 },
  { ko: '자유', en: 'freedom / liberty', topikLevel: 2 },
  { ko: '책임', en: 'responsibility', topikLevel: 2 },
  { ko: '권리', en: 'right (legal)', topikLevel: 2 },
  { ko: '의무', en: 'duty / obligation', topikLevel: 2 },
  { ko: '봉사', en: 'volunteer service', topikLevel: 2 },
  { ko: '기부', en: 'donation', topikLevel: 2 },
  { ko: '무역', en: 'trade / commerce', topikLevel: 2 },
  { ko: '수입', en: 'income / import', topikLevel: 2 },
  { ko: '수출', en: 'export', topikLevel: 2 },
  { ko: '물가', en: 'price level', topikLevel: 2 },
  { ko: '부자', en: 'rich person', topikLevel: 1 },
  { ko: '빈곤', en: 'poverty', topikLevel: 2 },

];
